### ISSUE TITLE
Diode next to Audio Jack?

### ISSUE THREAD

**Issue by ggrote** [toniebox-reverse-engineering/toniebox-pcb#1]
Thanks for the project, do you know what this component is? I think it's a diode, but not sure which one.
I got a Toniebox with a exploded diode and I want to replace it.
Thanks in advance!
![WhatsApp Image 2023-08-24 at 20 06 28](https://github.com/toniebox-reverse-engineering/toniebox-pcb/assets/10919361/c13b2079-ff87-4ebe-9c36-4a6d1e14e39f)

**Comment by SciLor** [comment]
This spot is very unusual. 
Usually, those parts only explode if they run on too much voltage/current. So the root problem will be something different. Therefore, I would check the power supply and the different voltage regulation parts.

**Comment by ggrote** [comment]
The first picture was from a Toniebox PCB that is okay. Here is a picture of the PCB with the exploded Diode:
![WhatsApp Image 2023-08-24 at 20 12 43](https://github.com/toniebox-reverse-engineering/toniebox-pcb/assets/10919361/7c2051eb-0dc4-4103-b77f-2e7459902696)

Could it be if someone puts a power supply with an audio jack cable into the headphone jack?
But I just need to know what diode it is to replace it. I think it says 5C, but I can't find it.

**Comment by SciLor** [comment]
This could be a possible reason.
Does the box still boot? (Not just glows green!)

PS: I would suggest you to continue in our telegram group https://t.me/toniebox_reverse_engineering

**Comment by ggrote** [comment]
The Box starts up, the Led is blinking red and there is no sound.

**Comment by ggrote** [comment]
I'm in the telegram group now. If you want you can delete the issue as it's not an issue with the github project.
Just got no other way to contact you. :)
